#!/bin/bash

# Laravel Install
laravel_install () {
    composer create-project --prefer-dist "laravel/laravel:^13.0" .

    sed -i'' -e "s/^\(# \)\?\(DB_CONNECTION=\).*/\2mysql/" .env
    sed -i'' -e "s/^\(# \)\?\(DB_HOST=\).*/\2db/" .env
    sed -i'' -e "s/^\(# \)\?\(DB_PORT=\).*/\23306/" .env
    sed -i'' -e "s/^\(# \)\?\(DB_DATABASE=\).*/\2laravel/" .env
    sed -i'' -e "s/^\(# \)\?\(DB_USERNAME=\).*/\2laravel-user/" .env
    sed -i'' -e "s/^\(# \)\?\(DB_PASSWORD=\).*/\2laravel-pass/" .env
    sed -i'' -e "s/^\(# \)\?\(MAIL_HOST=\).*/\2mailhog/" .env

    php artisan migrate
}

# New Starter Kit Install
# stack: react | vue | svelte | livewire
laravel_starter_kit_install () {
    local stack=${1:-livewire}

    case "$stack" in
        react)    using="laravel/react-starter-kit" ;;
        vue)      using="laravel/vue-starter-kit" ;;
        svelte)   using="laravel/svelte-starter-kit" ;;
        livewire) using="laravel/livewire-starter-kit" ;;
        *)
            echo "Unknown stack: $stack"
            echo "Available: react, vue, svelte, livewire"
            exit 1
            ;;
    esac

    composer create-project --prefer-dist "$using" .
    npm install
    npm run build
}

# Laravel Fortify Install
laravel_fortify_install () {
    options=$1
    composer require laravel/fortify
    php artisan fortify:install
    php artisan migrate:refresh
}

# Help
usage () {
  cat << EOM
Usage: $(basename "$0") [OPTION]...
      --kit             install new starter kit (default: livewire)
      --kit=STACK       install new starter kit STACK: react, vue, svelte, livewire
      --fortify         install Laravel Fortify (ignored if --kit is used)
  -h, --help            display this help and exit
  -v, --version         output version information and exit
EOM
}

# Version
version () {
    echo 'v2.0.0'
}

cd /var/www

use_kit=false
kit_stack='livewire'
use_fortify=false

while getopts :-: opt; do
    if [ "$opt" = - ]; then
        case "${OPTARG%%=*}" in
            kit)
                use_kit=true
                case "${OPTARG##*=}" in
                    react|vue|svelte|livewire)
                        kit_stack="${OPTARG##*=}"
                        ;;
                esac
                ;;
            fortify)
                use_fortify=true
                ;;
            help)
                usage
                exit
                ;;
            version)
                version
                exit
                ;;
            *)
                echo "$0: illegal option -- ${OPTARG%%=*}"
                usage
                exit 1
                ;;
        esac
    else
        case "$opt" in
            h) usage; exit ;;
            v) version; exit ;;
            *)
                echo "$0: illegal option -$opt"
                usage
                exit 1
                ;;
        esac
    fi
done

laravel_install

if "${use_kit}"; then
    laravel_starter_kit_install "${kit_stack}"
elif "${use_fortify}"; then
    laravel_fortify_install
fi